repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort

-   repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
    - id: pyupgrade
      args: ["--py37-plus"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      exclude: ^fuzz/generated/

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args: ["-c", "bandit.conf"]

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint

