name: 'CVE Binary Tool'
description: "CVE Binary Tool's official GitHub Action"
author: 'b31ngd3v'
branding:
  icon: 'shield'
  color: 'gray-dark'
inputs:
  nvd_api_key:
    required: false
    description: 'NVD API Key is required for downloading National Vulnerbility Database.'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: 'python3-pip'
    - run: pip install git+https://github.com/b31ngd3v/cve-bin-tool@fix_filepath reportlab
      shell: bash
    - run: >
        python3 "${GITHUB_ACTION_PATH}/src/scanner.py"
        --repo '${{ github.repository }}'
        --run-id '${{ github.run_id }}'
        --html-pdf-output "./scan-result"
        --sarif-output "/tmp/scan-report.sarif"
        --nvd-api-key '${{ inputs.nvd_api_key }}'
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: cve_reports
        path: |
          scan-result.html
          scan-result.pdf
        if-no-files-found: ignore
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: /tmp/scan-report.sarif
        category: cve-bin-tool
