name: Linting

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-22.04
    permissions:
      contents: write # for stefanzweifel/git-auto-commit-action to create a PR
    strategy:
      fail-fast: false
      matrix:
        tool: ['isort', 'black', 'pyupgrade', 'flake8', 'bandit', 'gitlint']
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4 # v3.5.3
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pre-commit
          pre-commit install
      - name: Run ${{ matrix.tool }} using pre-commit
        if: ${{ matrix.tool != 'gitlint' }}
        run: |
          pre-commit run ${{ matrix.tool }} --all-files
      - name: Run gitlint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        if: ${{ github.event_name == 'pull_request' && matrix.tool == 'gitlint' }}
        run: |
          python -m pip install --upgrade gitlint
          echo "$TITLE" | gitlint
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842

